cc_test(
    name = "test",
    srcs = [
        "rangequery_test.cc",
        "fastlog_test.cc",
        "sparsetable_test.cc",
    ],
    deps = [
        "//rangequery:rangequery",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
    size = "small",
)

