cc_library(
    name = "rangequery",
    srcs = [
        "rangequery.cc",
        "sparsetable.cc",
    ],
    hdrs = [
        "fastlog.h",
        "rangequery.h",
        "sparsetable.h",
    ],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/strings",
    ],
    visibility = ["//visibility:public"],
)
