cc_library(
    name = "competitive",
    srcs = [],
    hdrs = [],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/strings",
    ],
    visibility = ["//visibility:public"],
)

